<?php

/*
+---------------------------------------------------------------------------+
| Revive Adserver                                                           |
| http://www.revive-adserver.com                                            |
|                                                                           |
| Copyright: See the COPYRIGHT.txt file.                                    |
| License: GPLv2 or later, see the LICENSE.txt file.                        |
+---------------------------------------------------------------------------+
*/

// This is by no means a complete list of all iso3166 codes, but rather
// an unofficial list used by most browsers. If you have corrections or
// additions to this list, please send them to niels@creatype.nl

// Note this array has been updated to use the list supplied at:
// http://www.maxmind.com/app/iso3166

$phpAds_ISO3166['AD'] = "Andorra";
$phpAds_ISO3166['AE'] = "United Arab Emirates";
$phpAds_ISO3166['AF'] = "Afghanistan";
$phpAds_ISO3166['AG'] = "Antigua and Barbuda";
$phpAds_ISO3166['AI'] = "Anguilla";
$phpAds_ISO3166['AL'] = "Albania";
$phpAds_ISO3166['AM'] = "Armenia";
$phpAds_ISO3166['AN'] = "Netherlands Antilles";
$phpAds_ISO3166['AO'] = "Angola";
$phpAds_ISO3166['AP'] = "Asia/Pacific Region";
$phpAds_ISO3166['AQ'] = "Antarctica";
$phpAds_ISO3166['AR'] = "Argentina";
$phpAds_ISO3166['AS'] = "American Samoa";
$phpAds_ISO3166['AT'] = "Austria";
$phpAds_ISO3166['AU'] = "Australia";
$phpAds_ISO3166['AW'] = "Aruba";
$phpAds_ISO3166['AZ'] = "Azerbaijan";
$phpAds_ISO3166['BA'] = "Bosnia and Herzegovina";
$phpAds_ISO3166['BB'] = "Barbados";
$phpAds_ISO3166['BD'] = "Bangladesh";
$phpAds_ISO3166['BE'] = "Belgium";
$phpAds_ISO3166['BF'] = "Burkina Faso";
$phpAds_ISO3166['BG'] = "Bulgaria";
$phpAds_ISO3166['BH'] = "Bahrain";
$phpAds_ISO3166['BI'] = "Burundi";
$phpAds_ISO3166['BJ'] = "Benin";
$phpAds_ISO3166['BM'] = "Bermuda";
$phpAds_ISO3166['BN'] = "Brunei Darussalam";
$phpAds_ISO3166['BO'] = "Bolivia";
$phpAds_ISO3166['BR'] = "Brazil";
$phpAds_ISO3166['BS'] = "Bahamas";
$phpAds_ISO3166['BT'] = "Bhutan";
$phpAds_ISO3166['BV'] = "Bouvet Island";
$phpAds_ISO3166['BW'] = "Botswana";
$phpAds_ISO3166['BY'] = "Belarus";
$phpAds_ISO3166['BZ'] = "Belize";
$phpAds_ISO3166['CA'] = "Canada";
$phpAds_ISO3166['CC'] = "Cocos (Keeling) Islands";
$phpAds_ISO3166['CD'] = "Congo - The Democratic Republic of the";
$phpAds_ISO3166['CF'] = "Central African Republic";
$phpAds_ISO3166['CG'] = "Congo";
$phpAds_ISO3166['CH'] = "Switzerland";
$phpAds_ISO3166['CI'] = "Cote D'Ivoire";
$phpAds_ISO3166['CK'] = "Cook Islands";
$phpAds_ISO3166['CL'] = "Chile";
$phpAds_ISO3166['CM'] = "Cameroon";
$phpAds_ISO3166['CN'] = "China";
$phpAds_ISO3166['CO'] = "Colombia";
$phpAds_ISO3166['CR'] = "Costa Rica";
$phpAds_ISO3166['CU'] = "Cuba";
$phpAds_ISO3166['CV'] = "Cape Verde";
$phpAds_ISO3166['CX'] = "Christmas Island";
$phpAds_ISO3166['CY'] = "Cyprus";
$phpAds_ISO3166['CZ'] = "Czech Republic";
$phpAds_ISO3166['DE'] = "Germany";
$phpAds_ISO3166['DJ'] = "Djibouti";
$phpAds_ISO3166['DK'] = "Denmark";
$phpAds_ISO3166['DM'] = "Dominica";
$phpAds_ISO3166['DO'] = "Dominican Republic";
$phpAds_ISO3166['DZ'] = "Algeria";
$phpAds_ISO3166['EC'] = "Ecuador";
$phpAds_ISO3166['EE'] = "Estonia";
$phpAds_ISO3166['EG'] = "Egypt";
$phpAds_ISO3166['EH'] = "Western Sahara";
$phpAds_ISO3166['ER'] = "Eritrea";
$phpAds_ISO3166['ES'] = "Spain";
$phpAds_ISO3166['ET'] = "Ethiopia";
$phpAds_ISO3166['EU'] = "Europe";
$phpAds_ISO3166['FI'] = "Finland";
$phpAds_ISO3166['FJ'] = "Fiji";
$phpAds_ISO3166['FK'] = "Falkland Islands (Malvinas)";
$phpAds_ISO3166['FM'] = "Micronesia - Federated States of";
$phpAds_ISO3166['FO'] = "Faroe Islands";
$phpAds_ISO3166['FR'] = "France";
$phpAds_ISO3166['FX'] = "France - Metropolitan";
$phpAds_ISO3166['GA'] = "Gabon";
$phpAds_ISO3166['GB'] = "United Kingdom";
$phpAds_ISO3166['GD'] = "Grenada";
$phpAds_ISO3166['GE'] = "Georgia";
$phpAds_ISO3166['GF'] = "French Guiana";
$phpAds_ISO3166['GH'] = "Ghana";
$phpAds_ISO3166['GI'] = "Gibraltar";
$phpAds_ISO3166['GL'] = "Greenland";
$phpAds_ISO3166['GM'] = "Gambia";
$phpAds_ISO3166['GN'] = "Guinea";
$phpAds_ISO3166['GP'] = "Guadeloupe";
$phpAds_ISO3166['GQ'] = "Equatorial Guinea";
$phpAds_ISO3166['GR'] = "Greece";
$phpAds_ISO3166['GS'] = "South Georgia and the South Sandwich Islands";
$phpAds_ISO3166['GT'] = "Guatemala";
$phpAds_ISO3166['GU'] = "Guam";
$phpAds_ISO3166['GW'] = "Guinea-Bissau";
$phpAds_ISO3166['GY'] = "Guyana";
$phpAds_ISO3166['HK'] = "Hong Kong";
$phpAds_ISO3166['HM'] = "Heard Island and McDonald Islands";
$phpAds_ISO3166['HN'] = "Honduras";
$phpAds_ISO3166['HR'] = "Croatia";
$phpAds_ISO3166['HT'] = "Haiti";
$phpAds_ISO3166['HU'] = "Hungary";
$phpAds_ISO3166['ID'] = "Indonesia";
$phpAds_ISO3166['IE'] = "Ireland";
$phpAds_ISO3166['IL'] = "Israel";
$phpAds_ISO3166['IN'] = "India";
$phpAds_ISO3166['IO'] = "British Indian Ocean Territory";
$phpAds_ISO3166['IQ'] = "Iraq";
$phpAds_ISO3166['IR'] = "Iran - Islamic Republic of";
$phpAds_ISO3166['IS'] = "Iceland";
$phpAds_ISO3166['IT'] = "Italy";
$phpAds_ISO3166['JM'] = "Jamaica";
$phpAds_ISO3166['JO'] = "Jordan";
$phpAds_ISO3166['JP'] = "Japan";
$phpAds_ISO3166['KE'] = "Kenya";
$phpAds_ISO3166['KG'] = "Kyrgyzstan";
$phpAds_ISO3166['KH'] = "Cambodia";
$phpAds_ISO3166['KI'] = "Kiribati";
$phpAds_ISO3166['KM'] = "Comoros";
$phpAds_ISO3166['KN'] = "Saint Kitts and Nevis";
$phpAds_ISO3166['KP'] = "Korea - Democratic People's Republic of";
$phpAds_ISO3166['KR'] = "Korea - Republic of";
$phpAds_ISO3166['KW'] = "Kuwait";
$phpAds_ISO3166['KY'] = "Cayman Islands";
$phpAds_ISO3166['KZ'] = "Kazakhstan";
$phpAds_ISO3166['LA'] = "Lao People's Democratic Republic";
$phpAds_ISO3166['LB'] = "Lebanon";
$phpAds_ISO3166['LC'] = "Saint Lucia";
$phpAds_ISO3166['LI'] = "Liechtenstein";
$phpAds_ISO3166['LK'] = "Sri Lanka";
$phpAds_ISO3166['LR'] = "Liberia";
$phpAds_ISO3166['LS'] = "Lesotho";
$phpAds_ISO3166['LT'] = "Lithuania";
$phpAds_ISO3166['LU'] = "Luxembourg";
$phpAds_ISO3166['LV'] = "Latvia";
$phpAds_ISO3166['LY'] = "Libyan Arab Jamahiriya";
$phpAds_ISO3166['MA'] = "Morocco";
$phpAds_ISO3166['MC'] = "Monaco";
$phpAds_ISO3166['MD'] = "Moldova - Republic of";
$phpAds_ISO3166['MG'] = "Madagascar";
$phpAds_ISO3166['MH'] = "Marshall Islands";
$phpAds_ISO3166['MK'] = "Macedonia";
$phpAds_ISO3166['ML'] = "Mali";
$phpAds_ISO3166['MM'] = "Myanmar";
$phpAds_ISO3166['MN'] = "Mongolia";
$phpAds_ISO3166['MO'] = "Macau";
$phpAds_ISO3166['MP'] = "Northern Mariana Islands";
$phpAds_ISO3166['MQ'] = "Martinique";
$phpAds_ISO3166['MR'] = "Mauritania";
$phpAds_ISO3166['MS'] = "Montserrat";
$phpAds_ISO3166['MT'] = "Malta";
$phpAds_ISO3166['MU'] = "Mauritius";
$phpAds_ISO3166['MV'] = "Maldives";
$phpAds_ISO3166['MW'] = "Malawi";
$phpAds_ISO3166['MX'] = "Mexico";
$phpAds_ISO3166['MY'] = "Malaysia";
$phpAds_ISO3166['MZ'] = "Mozambique";
$phpAds_ISO3166['NA'] = "Namibia";
$phpAds_ISO3166['NC'] = "New Caledonia";
$phpAds_ISO3166['NE'] = "Niger";
$phpAds_ISO3166['NF'] = "Norfolk Island";
$phpAds_ISO3166['NG'] = "Nigeria";
$phpAds_ISO3166['NI'] = "Nicaragua";
$phpAds_ISO3166['NL'] = "Netherlands";
$phpAds_ISO3166['NO'] = "Norway";
$phpAds_ISO3166['NP'] = "Nepal";
$phpAds_ISO3166['NR'] = "Nauru";
$phpAds_ISO3166['NU'] = "Niue";
$phpAds_ISO3166['NZ'] = "New Zealand";
$phpAds_ISO3166['OM'] = "Oman";
$phpAds_ISO3166['PA'] = "Panama";
$phpAds_ISO3166['PE'] = "Peru";
$phpAds_ISO3166['PF'] = "French Polynesia";
$phpAds_ISO3166['PG'] = "Papua New Guinea";
$phpAds_ISO3166['PH'] = "Philippines";
$phpAds_ISO3166['PK'] = "Pakistan";
$phpAds_ISO3166['PL'] = "Poland";
$phpAds_ISO3166['PM'] = "Saint Pierre and Miquelon";
$phpAds_ISO3166['PN'] = "Pitcairn";
$phpAds_ISO3166['PR'] = "Puerto Rico";
$phpAds_ISO3166['PS'] = "Palestinian Territory - Occupied";
$phpAds_ISO3166['PT'] = "Portugal";
$phpAds_ISO3166['PW'] = "Palau";
$phpAds_ISO3166['PY'] = "Paraguay";
$phpAds_ISO3166['QA'] = "Qatar";
$phpAds_ISO3166['RE'] = "Reunion";
$phpAds_ISO3166['RO'] = "Romania";
$phpAds_ISO3166['RU'] = "Russian Federation";
$phpAds_ISO3166['RW'] = "Rwanda";
$phpAds_ISO3166['SA'] = "Saudi Arabia";
$phpAds_ISO3166['SB'] = "Solomon Islands";
$phpAds_ISO3166['SC'] = "Seychelles";
$phpAds_ISO3166['SD'] = "Sudan";
$phpAds_ISO3166['SE'] = "Sweden";
$phpAds_ISO3166['SG'] = "Singapore";
$phpAds_ISO3166['SH'] = "Saint Helena";
$phpAds_ISO3166['SI'] = "Slovenia";
$phpAds_ISO3166['SJ'] = "Svalbard and Jan Mayen";
$phpAds_ISO3166['SK'] = "Slovakia";
$phpAds_ISO3166['SL'] = "Sierra Leone";
$phpAds_ISO3166['SM'] = "San Marino";
$phpAds_ISO3166['SN'] = "Senegal";
$phpAds_ISO3166['SO'] = "Somalia";
$phpAds_ISO3166['SR'] = "Suriname";
$phpAds_ISO3166['ST'] = "Sao Tome and Principe";
$phpAds_ISO3166['SV'] = "El Salvador";
$phpAds_ISO3166['SY'] = "Syrian Arab Republic";
$phpAds_ISO3166['SZ'] = "Swaziland";
$phpAds_ISO3166['TC'] = "Turks and Caicos Islands";
$phpAds_ISO3166['TD'] = "Chad";
$phpAds_ISO3166['TF'] = "French Southern Territories";
$phpAds_ISO3166['TG'] = "Togo";
$phpAds_ISO3166['TH'] = "Thailand";
$phpAds_ISO3166['TJ'] = "Tajikistan";
$phpAds_ISO3166['TK'] = "Tokelau";
$phpAds_ISO3166['TL'] = "East Timor";
$phpAds_ISO3166['TM'] = "Turkmenistan";
$phpAds_ISO3166['TN'] = "Tunisia";
$phpAds_ISO3166['TO'] = "Tonga";
$phpAds_ISO3166['TR'] = "Turkey";
$phpAds_ISO3166['TT'] = "Trinidad and Tobago";
$phpAds_ISO3166['TV'] = "Tuvalu";
$phpAds_ISO3166['TW'] = "Taiwan - Province of China";
$phpAds_ISO3166['TZ'] = "Tanzania - United Republic of";
$phpAds_ISO3166['UA'] = "Ukraine";
$phpAds_ISO3166['UG'] = "Uganda";
$phpAds_ISO3166['UM'] = "United States Minor Outlying Islands";
$phpAds_ISO3166['US'] = "United States";
$phpAds_ISO3166['UY'] = "Uruguay";
$phpAds_ISO3166['UZ'] = "Uzbekistan";
$phpAds_ISO3166['VA'] = "Holy See (Vatican City State)";
$phpAds_ISO3166['VC'] = "Saint Vincent and the Grenadines";
$phpAds_ISO3166['VE'] = "Venezuela";
$phpAds_ISO3166['VG'] = "Virgin Islands - British";
$phpAds_ISO3166['VI'] = "Virgin Islands - U.S.";
$phpAds_ISO3166['VN'] = "Vietnam";
$phpAds_ISO3166['VU'] = "Vanuatu";
$phpAds_ISO3166['WF'] = "Wallis and Futuna";
$phpAds_ISO3166['WS'] = "Samoa";
$phpAds_ISO3166['YE'] = "Yemen";
$phpAds_ISO3166['YT'] = "Mayotte";
$phpAds_ISO3166['YU'] = "Yugoslavia";
$phpAds_ISO3166['ZA'] = "South Africa";
$phpAds_ISO3166['ZM'] = "Zambia";
$phpAds_ISO3166['ZR'] = "Zaire";
$phpAds_ISO3166['ZW'] = "Zimbabwe";

asort($phpAds_ISO3166);

$phpAds_ISO3166['A1'] = "Anonymous Proxy";
$phpAds_ISO3166['A2'] = "Satellite Provider";

// Load localized strings
if (file_exists(MAX_PATH.'/lib/max/language/'.$pref['language'].'/res-iso3166.lang.php'))
	@include(MAX_PATH.'/lib/max/language/'.$pref['language'].'/res-iso3166.lang.php');

?>
