    <name>{NAME}</name>
    <creationDate>{DATE}</creationDate>
    <author>{AUTHOR}</author>
    <authorEmail>{EMAIL}</authorEmail>
    <authorUrl>{URL}</authorUrl>
    <license>{LICENCE}</license>
    <description>{DESCRIPTION}</description>
    <version>{VERSION}</version>
    <oxversion>{OXVERSION}</oxversion>