DROP TABLE IF EXISTS 
    acls,
    ad_zone_assoc,
    affiliates,
    affiliates_extra, 
    agency, 
    banners, 
    campaigns, 
    channel, 
    clients, 
    images, 
    log_maintenance_statistics,
    placement_zone_assoc, 
    preference, 
    zones;
