<?php

/*
+---------------------------------------------------------------------------+
| Revive Adserver                                                           |
| http://www.revive-adserver.com                                            |
|                                                                           |
| Copyright: See the COPYRIGHT.txt file.                                    |
| License: GPLv2 or later, see the LICENSE.txt file.                        |
+---------------------------------------------------------------------------+
*/

/**
 * OpenX Schema Management Utility
 */

function onclickUpOrDown($param)
{
	$objResponse = new xajaxResponse();

	if ($param=='up')
	{
    	$objResponse->addAssign('img_up',"style.display", 'none');
    	$objResponse->addAssign('img_down',"style.display", 'inline');
	}
	else
	{
    	$objResponse->addAssign('img_up',"style.display", 'inline');
    	$objResponse->addAssign('img_down',"style.display", 'none');
	}
	return $objResponse;
}

function ajaxAlert($event)
{
	$objResponse = new xajaxResponse();
	$objResponse->addAlert($event.' event detected');

	return $objResponse;
}


require_once MAX_PATH.'/lib/xajax/xajax.inc.php';

$xajax = new xajax();
//$xajax->debugOn(); // Uncomment this line to turn debugging on
$xajax->debugOff(); // Uncomment this line to turn debugging off
$xajax->registerFunction("onclickUpOrDown");
$xajax->registerFunction("ajaxAlert");

// Process any requests.  Because our requestURI is the same as our html page,
// this must be called before any headers or HTML output have been sent
$xajax->processRequests();

$overwrite=true;

$jspath = MAX_PATH.'/var/plugins/cache/';
$jsfile = 'demoXajax.js';
if (!file_exists($jspath.$jsfile) || $overwrite)
{
    ob_start();
    $xajax->printJavascript($jspath, $jsfile); // output the xajax javascript. This must be called between the head tags
    $js = ob_get_contents();
    ob_end_clean();

    $pattern    = '/(<script type="text\/javascript">)(?P<jscript>[\w\W\s]+)(<\/script>)/U';
	if (preg_match($pattern, $js, $aMatch))
	{
        $js = $aMatch['jscript'];
	}
	else
	{
        echo "Error parsing javascript generated by xAjax.  You should check the {$jspath}{$jsfile} manually.";
	}
	//$js.=';oxAjaxLoaded=true;';
	//$js.= ";alert('oxSchema.js loaded');";

    $fp = fopen($jspath.$jsfile, 'w');
    if ($fp === false) {
        echo "Error opening output file {$jspath}{$jsfile} for writing.  Check permissions.";
        die();
    }
    else
    {
        fwrite($fp, $js);
        fclose($fp);
    }
}


?>
