<?php
class OX_M2M_XmlRpcErrorCodes
{
	static $ACCOUNT_TYPE_NOT_ALLOWED = 821;
	static $PASSWORD_ALREADY_GENERATED = 822;
	static $PASSWORD_INVALID = 823;
	static $PASSWORD_EXPIRED = 824;
	static $CANNOT_CONNECT = 825;
	static $CANNOT_RECONNECT = 826;
	static $TICKET_EXPIRED = 827;
}
?>
