;<?php exit; ?>
;*** DO NOT REMOVE THE LINE ABOVE ***
[openads]
installed=1
requireSSL=
sslPort=443
[max]
installed=
uiEnabled=1
language=english
[database]
type=mysql
host=@db.host
port=@db.port
username=@db.login
password=@db.password
name=@db.name
persistent=
mysql4_compatibility=1
protocol=tcp
[databaseMysql]
statisticsSortBufferSize=
[timezone]
location=Europe/Warsaw
[webpath]
admin=@wt.host:@wt.port/@wt.basepath/admin
delivery=@wt.host:@wt.port/@wt.basepath/delivery
deliverySSL=@wt.host:@wt.port/@wt.basepath/delivery
images=@wt.host:@wt.port/@wt.basepath/images
imagesSSL=@wt.host:@wt.port/@wt.basepath/images
[file]
click=ck.php
conversionvars=tv.php
content=ac.php
conversion=ti.php
conversionjs=tjs.php
flash=fl.js
google=ag.php
frame=afr.php
image=ai.php
js=ajs.php
layer=al.php
log=lg.php
popup=apu.php
view=avw.php
xmlrpc=axmlrpc.php
local=alocal.php
frontcontroller=fc.php
[store]
mode=0
webDir=@webDir
ftpHost=
ftpPath=
ftpUsername=
ftpPassword=
ftpPassive=
[origin]
type=
host=
port=80
script=/www/delivery/dxmlrpc.php
timeout=10
protocol=http
[delivery]
cacheExpire=1200
cachePath=
acls=1
obfuscate=
execPhp=
ctDelimiter=__
chDelimiter=","
keywords=
cgiForceStatusHeader=
[p3p]
policies=1
compactPolicy=CUR ADM OUR NOR STA NID
policyLocation=
[graphs]
ttfDirectory=
ttfName=
[logging]
adRequests=
adImpressions=1
adClicks=1
trackerImpressions=1
reverseLookup=
proxyLookup=1
sniff=
defaultImpressionConnectionWindow=
defaultClickConnectionWindow=
blockAdImpressions=0
blockAdClicks=0
blockTrackerImpressions=0
logInUTC=
ignoreHosts=
ignoreUserAgents=
enforceUserAgents=
[modules]
AdServer=1
Tracker=1
[maintenance]
autoMaintenance=1
autoMaintenanceDelay=5
timeLimitScripts=300
operationInterval=60
compactStats=1
compactStatsGrace=604800
channelForecasting=
pruneCompletedCampaignsSummaryData=
[priority]
instantUpdate=1
useZonePatterning=
defaultZoneForecastImpressions=10
defaultClickRatio=0.005
defaultConversionRatio=0.0001
randmax=2147483647
[table]
prefix=ox_
split=
lockfile=
type=MYISAM
acls=acls
acls_channel=acls_channel
ad_category_assoc=ad_category_assoc
ad_zone_assoc=ad_zone_assoc
affiliates=affiliates
affiliates_extra=affiliates_extra
agency=agency
application_variable=application_variable
banners=banners
campaigns=campaigns
campaigns_trackers=campaigns_trackers
category=category
channel=channel
clients=clients
data_intermediate_ad=data_intermediate_ad
data_intermediate_ad_connection=data_intermediate_ad_connection
data_intermediate_ad_variable_value=data_intermediate_ad_variable_value
data_raw_ad_click=data_raw_ad_click
data_raw_ad_impression=data_raw_ad_impression
data_raw_ad_request=data_raw_ad_request
data_raw_tracker_click=data_raw_tracker_click
data_raw_tracker_impression=data_raw_tracker_impression
data_raw_tracker_variable_value=data_raw_tracker_variable_value
data_summary_ad_hourly=data_summary_ad_hourly
data_summary_ad_zone_assoc=data_summary_ad_zone_assoc
data_summary_channel_daily=data_summary_channel_daily
data_summary_zone_country_daily=data_summary_zone_country_daily
data_summary_zone_country_forecast=data_summary_zone_country_forecast
data_summary_zone_country_monthly=data_summary_zone_country_monthly
data_summary_zone_domain_page_daily=data_summary_zone_domain_page_daily
data_summary_zone_domain_page_forecast=data_summary_zone_domain_page_forecast
data_summary_zone_domain_page_monthly=data_summary_zone_domain_page_monthly
data_summary_zone_impression_history=data_summary_zone_impression_history
data_summary_zone_site_keyword_daily=data_summary_zone_site_keyword_daily
data_summary_zone_site_keyword_forecast=data_summary_zone_site_keyword_forecast
data_summary_zone_site_keyword_monthly=data_summary_zone_site_keyword_monthly
data_summary_zone_source_daily=data_summary_zone_source_daily
data_summary_zone_source_forecast=data_summary_zone_source_forecast
data_summary_zone_source_monthly=data_summary_zone_source_monthly
images=images
lb_local=lb_local
log_maintenance_forecasting=log_maintenance_forecasting
log_maintenance_priority=log_maintenance_priority
log_maintenance_statistics=log_maintenance_statistics
password_recovery=password_recovery
placement_zone_assoc=placement_zone_assoc
plugins_channel_delivery_assoc=plugins_channel_delivery_assoc
plugins_channel_delivery_domains=plugins_channel_delivery_domains
plugins_channel_delivery_rules=plugins_channel_delivery_rules
preference=preference
preference_advertiser=preference_advertiser
preference_publisher=preference_publisher
session=session
targetstats=targetstats
trackers=trackers
tracker_append=tracker_append
userlog=userlog
variables=variables
variable_publisher=variable_publisher
zones=zones
[splitTables]
data_raw_ad_click=1
data_raw_ad_impression=1
data_raw_ad_request=1
data_raw_tracker_click=1
data_raw_tracker_impression=1
data_raw_tracker_variable_value=1
[log]
enabled=1
methodNames=
lineNumbers=
type=file
name=debug.log
priority=PEAR_LOG_INFO
ident=OX
paramsUsername=
paramsPassword=
fileMode=0644
[deliveryLog]
enabled=
name=delivery.log
fileMode=0644
[cookie]
permCookieSeconds=31536000
[debug]
logfile=
production=1
sendErrorEmails=
emailSubject=Error from OpenX
email=email@example.com
emailAdminThreshold=PEAR_LOG_ERR
errorOverride=1
showBacktrace=
[var]
prefix=OA_
cookieTest=ct
cacheBuster=cb
channel=source
dest=oadest
logClick=log
n=n
params=oaparams
viewerId=OAID
campaignId=campaignid
adId=bannerid
creativeId=cid
zoneId=zoneid
blockAd=OABLOCK
capAd=OACAP
sessionCapAd=OASCAP
blockCampaign=OACBLOCK
capCampaign=OACCAP
sessionCapCampaign=OASCCAP
blockZone=OAZBLOCK
capZone=OAZCAP
sessionCapZone=OASZCAP
vars=OAVARS
trackonly=trackonly
openads=openads
[lb]
enabled=
type=mysql
host=localhost
port=3306
username=
password=
name=
persistent=
compactStats=1
compactStatsGrace=604800
[sync]
host=sync.openx.org
script=/xmlrpc.php
port=80
[dashboard]
protocol=http://
host=sync.openx.org
path=/dashboard-sync/dashboard/dashboard_iframe.php
[channelDerivation]
cacheExpire=86400
cachePath=/var/plugins/cache/channelDerivation/
xmlrpcScript=/www/delivery/delivery-xmlrpc.php
[geotargeting]
type="none"
saveStats=
geoipCountryLocation=
geoipRegionLocation=
geoipCityLocation=
geoipAreaLocation=
geoipDmaLocation=
geoipOrgLocation=
geoipIspLocation=
geoipNetspeedLocation=
